[project]
name = "nornflow"
version = "0.0.1"
author = "André Lima"
description = "For the moment, just a tiny CLI wrapper around Nornir"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "nornir>=3.5.0",
]
