[project]
name = "nornflow"
version = "0.0.1"
author = "André Lima"
description = "For the moment, just a tiny CLI wrapper around Nornir"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "nornir>=3.5.0",
    "nornir-utils>=0.2.0",
    "python-dotenv>=1.0.1",
    "pyyaml>=6.0.2",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "isort>=6.0.0",
    "mypy>=1.15.0",
    "ruff>=0.9.4",
]

[tool.ruff]
line-length = 110
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "A",
    "ANN003",
    "ANN204",
    "ANN205",
    "ANN401",
    "ARG",
    "BLE001",
    "C901",
    "COM",
    "D",
    "EM",
    "ERA001",
    "FBT001",
    "FBT003",
    "G004",
    "PLW2901",
    "RET504",
    "RSE",
    "SIM102",
    "TCH",
    "TRY003",
    "TRY400",
    "PLR0915",
    "PLE0604"
]
extend-select = ["I"]

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint.isort]
case-sensitive = false
order-by-type = false
combine-as-imports = true
no-lines-before = ["local-folder"]

[tool.black]
line-length = 110

[tool.isort]
profile = "black"